global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gfs-naming
    static_configs:
      - targets:
          - naming:8000

  - job_name: gfs-storage
    static_configs:
      - targets:
          - storage1:8000
          - storage2:8000
          - storage3:8000
          - storage4:8000
